version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nomadax-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nomadax
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - nomadax_data:/var/lib/mysql
      - ./init/nomadaxbkp.sql:/docker-entrypoint-initdb.d/nomadaxbkp.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  nomadax_data:
